### ISSUE TITLE
Какое ТЗ проекта?

### ISSUE THREAD

**Issue by PyAndrey** [YaroslavVolvach/Online-store#1]
За какую задачу могу взяться?

**Comment by YaroslavVolvach** [comment]
Ты можешь и в Телеграме писать если хочешь

пн, 14 дек. 2020 г., 12:19 Andrei <notifications@github.com>:

**Comment by YaroslavVolvach** [comment]
Что хочешь сделать? Можем начать новый проект если хочешь

пн, 14 дек. 2020 г., 12:21 Ярослав <volvachya@gmail.com>:

**Comment by PyAndrey** [comment]
Ок
